const data ={
    products:[
        {
            _id : "1",
            name : "Nike Slim Shirt",
            category : "Shirts",
            image :"/images/p1.jpg",
            price:65,
            brand :'Nike',
            rating :4.5,
            numReviews:10,
            description:'high quality product', 
        },
        {
            _id : "2",
            name : "Adidas Blabla",
            category : "Pants",
            image :"/images/p2.jpg",
            price:120,
            brand :'Adidas',
            rating :4,
            numReviews:10,
            description:'high quality product', 
        },
        {
            _id : "3",
            name : "Puma ooo",
            image :"/images/p3.jpg",
            price:120,
            brand :'louis',
            rating :5,
            numReviews:10,
            description:'high quality product', 
        },
        {
            _id : "4",
            name : "TinVu Happy",
            image :"/images/p4.jpg",
            price:300,
            brand :'Nike',
            rating :3.5,
            numReviews:10,
            description:'high quality product', 
        },
        {
            _id : "6",
            name : "Nike Slim Shirt",
            image :"/images/p5.jpg",
            price:120,
            brand :'Nike',
            rating :4.5,
            numReviews:10,
            description:'high quality product', 
        },
        {
            _id : "5",
            name : "Nike Slim Shirt",
            image :"/images/p6.jpg",
            price:90,
            brand :'Nike',
            rating :4.5,
            numReviews:6,
            description:'high quality product', 
        },
    ]
}
export default data;